#!/bin/bash
# 若SRC位置最后没有加/,则将SRC目录拷过去，若加了斜杠，则只拷贝SRC目录下的内容，SRC目录本身不拷贝。DEST位置加不加/没有什么区别。

# par
rsync -av -t -h -P --exclude '*.*~' --exclude '*.root' /Volumes/AppleData/CodeProject/Work/ribll/par \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/

# exp1

## map
### main.cc
rsync -av -t -h -P --exclude '*.*~' --exclude '*.root' --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp1/map/main.* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/map/
### include
rsync -av -t -h -P --exclude '*.*~' --exclude '*.root' --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp1/map/*.h* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/map/include/
rsync -av -t -h -P --exclude '*.*~' --exclude '*.root' --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp1/map/*.H* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/map/include/
### src
rsync -av -t -h -P --exclude '*.*~' --exclude '*.root' --exclude ".pro*" --exclude "main.*" /Volumes/AppleData/CodeProject/Work/ribll/exp1/map/*.c* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/map/src/
rsync -av -t -h -P --exclude '*.*~' --exclude '*.root' --exclude ".pro*" --exclude "main.*" /Volumes/AppleData/CodeProject/Work/ribll/exp1/map/*.C* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/map/src/


## cali
### main.cc
rsync -av -t -h -P --exclude '*.*~' --exclude '*.root' --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp1/cali/main.* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/cali/
### include
rsync -av -t -h -P --exclude '*.*~' --exclude '*.root' --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp1/cali/*.h* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/cali/include/
rsync -av -t -h -P --exclude '*.*~' --exclude '*.root' --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp1/cali/*.H* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/cali/include/
### src
rsync -av -t -h -P --exclude '*.*~' --exclude '*.root' --exclude ".pro*" --exclude "main.*" /Volumes/AppleData/CodeProject/Work/ribll/exp1/cali/*.c* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/cali/src/
rsync -av -t -h -P --exclude '*.*~' --exclude '*.root' --exclude ".pro*" --exclude "main.*" /Volumes/AppleData/CodeProject/Work/ribll/exp1/cali/*.C* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/cali/src/

## cut
### main.cc
rsync -av -t -h -P --exclude '*.*~' --exclude '*.root' --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp1/cut/main.* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/cut/
### include
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp1/cut/*.h* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/cut/include/
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp1/cut/*.H* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/cut/include/
### src
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" --exclude "main.*" /Volumes/AppleData/CodeProject/Work/ribll/exp1/cut/*.c* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/cut/src/
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" --exclude "main.*" /Volumes/AppleData/CodeProject/Work/ribll/exp1/cut/*.C* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/cut/src/

## corr
### main.cc
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp1/corr/main.* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/corr/
### include
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp1/corr/*.h* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/corr/include/
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp1/corr/*.H* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/corr/include/
### src
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" --exclude "main.*" /Volumes/AppleData/CodeProject/Work/ribll/exp1/corr/*.c* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/corr/src/
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" --exclude "main.*" /Volumes/AppleData/CodeProject/Work/ribll/exp1/corr/*.C* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/corr/src/

# exp2

## map
### main.cc
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp2/map/main.* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/map/
### include
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp2/map/*.h* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/map/include/
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp2/map/*.H* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/map/include/
### src
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" --exclude "main.*" /Volumes/AppleData/CodeProject/Work/ribll/exp2/map/*.c* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/map/src/
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" --exclude "main.*" /Volumes/AppleData/CodeProject/Work/ribll/exp2/map/*.C* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/map/src/

## cali
### main.cc
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp2/cali/main.* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/cali/
### include
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp2/cali/*.h* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/cali/include/
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp2/cali/*.H* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/cali/include/
### src
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" --exclude "main.*" /Volumes/AppleData/CodeProject/Work/ribll/exp2/cali/*.c* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/cali/src/
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" --exclude "main.*" /Volumes/AppleData/CodeProject/Work/ribll/exp2/cali/*.C* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/cali/src/

## cut
### main.cc
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp2/cut/main.* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/cut/
### include
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp2/cut/*.h* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/cut/include/
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp2/cut/*.H* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/cut/include/
### src
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" --exclude "main.*" /Volumes/AppleData/CodeProject/Work/ribll/exp2/cut/*.c* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/cut/src/
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" --exclude "main.*" /Volumes/AppleData/CodeProject/Work/ribll/exp2/cut/*.C* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/cut/src/

## corr
### main.cc
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp2/corr/main.* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/corr/
### include
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp2/corr/*.h* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/corr/include/
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" /Volumes/AppleData/CodeProject/Work/ribll/exp2/corr/*.H* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/corr/include/
### src
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" --exclude "main.*" /Volumes/AppleData/CodeProject/Work/ribll/exp2/corr/*.c* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/corr/src/
rsync -av -t -h -P --exclude '*.*~'  --exclude ".pro*" --exclude "main.*" /Volumes/AppleData/CodeProject/Work/ribll/exp2/corr/*.C* \
-e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/corr/src/
