#!/bin/bash
# 若SRC位置最后没有加/,则将SRC目录拷过去，若加了斜杠，则只拷贝SRC目录下的内容，SRC目录本身不拷贝。DEST位置加不加/没有什么区别。

# par
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/par \
/Volumes/AppleData/CodeProject/Work/ribll/


# exp1

## map
### main.cc
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/map/main.*  \
/Volumes/AppleData/CodeProject/Work/ribll/exp1/map/

### include
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/map/include/* \
/Volumes/AppleData/CodeProject/Work/ribll/exp1/map/

### src
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/map/src/* \
/Volumes/AppleData/CodeProject/Work/ribll/exp1/map/




## cali
### main.cc
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/cali/main.*  \
/Volumes/AppleData/CodeProject/Work/ribll/exp1/cali/
### include
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/cali/include/* \
/Volumes/AppleData/CodeProject/Work/ribll/exp1/cali/
### src
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/cali/src/* \
/Volumes/AppleData/CodeProject/Work/ribll/exp1/cali/

## cut
### main.cc
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/cut/main.*  \
/Volumes/AppleData/CodeProject/Work/ribll/exp1/cut/
### include
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/cut/include/* \
/Volumes/AppleData/CodeProject/Work/ribll/exp1/cut/
### src
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/cut/src/* \
/Volumes/AppleData/CodeProject/Work/ribll/exp1/cut/

## corr
### main.cc
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/corr/main.*  \
/Volumes/AppleData/CodeProject/Work/ribll/exp1/corr/
### include
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/corr/include/* \
/Volumes/AppleData/CodeProject/Work/ribll/exp1/corr/
### src
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/exp1code/corr/src/* \
/Volumes/AppleData/CodeProject/Work/ribll/exp1/corr/

# exp2

## map
### main.cc
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/map/main.* \
/Volumes/AppleData/CodeProject/Work/ribll/exp2/map/
### include
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/map/include/* \
/Volumes/AppleData/CodeProject/Work/ribll/exp2/map/
### src
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/map/src/* \
/Volumes/AppleData/CodeProject/Work/ribll/exp2/map/

## cali
### main.cc
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/cali/main.* \
/Volumes/AppleData/CodeProject/Work/ribll/exp2/cali/
### include
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/cali/include/* \
/Volumes/AppleData/CodeProject/Work/ribll/exp2/cali/
### src
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/cali/src/* \
/Volumes/AppleData/CodeProject/Work/ribll/exp2/cali/

## cut
### main.cc
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/cut/main.* \
/Volumes/AppleData/CodeProject/Work/ribll/exp2/cut/
### include
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/cut/include/* \
/Volumes/AppleData/CodeProject/Work/ribll/exp2/cut/
### src
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/cut/src/* \
/Volumes/AppleData/CodeProject/Work/ribll/exp2/cut/

## corr
### main.cc
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/corr/main.* \
/Volumes/AppleData/CodeProject/Work/ribll/exp2/corr/
### include
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/corr/include/* \
/Volumes/AppleData/CodeProject/Work/ribll/exp2/corr/
### src
rsync -av -t -h -P --exclude '*.*~' -e "ssh -p 2727" wuchenguang@162.105.151.29:/data/d1/RIBLL2017NaMgAlSi/yfs/corr/src/* \
/Volumes/AppleData/CodeProject/Work/ribll/exp2/corr/
